[profile.default]
  optimizer = true
  optimizer_runs = 10_000_000
  solc_version = "0.8.16"
  verbosity = 3

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests duriscopng development.
  optimizer = false

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
